[ClassVersion("1.0"), FriendlyName("ADServiceAccount")] 
class SIOS_ADServiceAccount : OMI_BaseResource
{
    [Key] string DomainName;
    [Key] string ServiceName;
    [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
    [write] string DNSHostname;
    [required,EmbeddedInstance("MSFT_Credential")] string DomainAdministratorCredential;
};
